Repository iver-wharf/wharf-api, pull requests merged in 2021-09, with the labels that each got.

#55 Removed constraint of "cannot change group"
  CHANGELOG.md
  project.go
Labels: enhancement

#54 Fixed project & build JSON marshal regression
  CHANGELOG.md
  build.go
  buildstatus.go
  database.go
  database_models.go
  database_models_json.go
  database_models_json_test.go
  utils.go
  utils_test.go
Labels: bug

#59 Rely on Docker images latest patch version
  CHANGELOG.md
  Dockerfile
Labels: bug

#52 Changed to use wharf-core/pkg/cacertutil instead of internal/httputils
  CHANGELOG.md
  go.mod
  go.sum
  internal/httputils/httpclient.go
  main.go
Labels: enhancement

#57 Removed unused code
  CHANGELOG.md
  main.go
  utils.go
  utils_test.go
Labels: enhancement

#58 Release v4.2.0
  CHANGELOG.md
Labels: release

#60 Release v4.2.0 (with fixed date)
  CHANGELOG.md
Labels: release

#63 Fixed so gin logger intration is setup before it's used
  CHANGELOG.md
  main.go
Labels: enhancement

#61 Added "--pull" to docker build
  Makefile
Labels: enhancement

#64 Fixed cannot delete projects
  CHANGELOG.md
  database_models.go
  migrations.go
Labels: bug

#43 Reworked handling of test results
  CHANGELOG.md
  README.md
  artifact.go
  build.go
  database_models.go
  go.mod
  go.sum
  internal/ctxparser/ctxparser.go
  migrations.go
  project.go
  test_result.go
Labels: enhancement

#76 Changed path params to camelCase
  CHANGELOG.md
  artifact.go
  branch.go
  build.go
  project.go
  provider.go
  test_result.go
  token.go
Labels: documentation

#75 Deprecated GET /branch/{branchid}
  CHANGELOG.md
  branch.go
  internal/deprecated/branch.go
Labels: enhancement

#77 Fixed some things missed in PR #43
  CHANGELOG.md
  artifact.go
  database_models.go
Labels: bug, documentation

#78 Split up DB models: part 1
  CHANGELOG.md
  artifact.go
  branch.go
  build.go
  database_models.go
  migrations.go
  pkg/model/database/database.go
  pkg/model/request/request.go
  pkg/model/response/response.go
  project.go
  provider.go
  token.go
Labels: enhancement

#79 Added swaggo operation ID & renamed handlers
  CHANGELOG.md
  artifact.go
  branch.go
  build.go
  ping.go
  project.go
  provider.go
  test_result.go
  token.go
  version.go
Labels: documentation

#80 Fixed N+1 Build and TestResult fetch issue
  CHANGELOG.md
  branch.go
  build.go
  database_models.go
  pkg/model/database/database.go
  project.go
Labels: enhancement

#82 Removed Provider.UploadURL
  CHANGELOG.md
  database_models.go
  migrations.go
  pkg/model/database/database.go
  provider.go
Labels: enhancement

#85 Added config for local dev purpose
  wharf-api-config.yml
Labels: enhancement

#84 Makefile: only run 'swag init' if needed
  Makefile
Labels: enhancement
