Repository iver-wharf/wharf-api, pull requests merged in 2021-05, with the labels that each got.

#1 Added repo
  .dockerignore
  .editorconfig
  .gitignore
  .wharf-ci.yml
  CHANGELOG.md
  Dockerfile
  artifact.go
  branch.go
  build.go
  buildstatus.go
  database.go
  database_models.go
  database_test.go
  go.mod
  go.sum
  main.go
  messagequeue.go
  migrations.go
  module.go
  ping.go
  pkg/httputils/httpclient.go
  pkg/httputils/params.go
  pkg/orderby/direction.go
  pkg/orderby/example_test.go
  pkg/orderby/gorm.db
  pkg/orderby/orderby.go
  pkg/orderby/orderby_test.go
  pkg/problem/docsurl.go
  pkg/problem/docsurl_example_test.go
  pkg/problem/recover.go
  pkg/problem/response.go
  pkg/problem/write.go
  pkg/problem/write_example_test.go
  project.go
  project_test.go
  provider.go
  token.go
  utils.go
  utils_test.go
Labels: enhancement

#4 Added remark-lint
  .dockerignore
  .gitignore
  .remarkrc
  CHANGELOG.md
  README.md
  package.json
Labels: documentation

#3 Added README
  README.md
Labels: documentation

#5 Ignore .idea directory
  .dockerignore
  .gitignore
Labels: enhancement

#6 Fixed two problem responses
  project.go
Labels: enhancement

#20 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#21 Added Codacy badge & Revive linting
  README.md
  build.go
  database.go
  database_models.go
  migrations.go
  package.json
  pkg/orderby/orderby.go
  project.go
  revive.toml
  token.go
  utils.go
  utils_test.go
Labels: documentation, enhancement

#2 Added version endpoint
  .wharf-ci.yml
  CHANGELOG.md
  Dockerfile
  README.md
  deploy/update-version.sh
  go.mod
  go.sum
  main.go
  version.go
  version.yaml
Labels: enhancement

#24 Release v4.0.0
  CHANGELOG.md
Labels: enhancement
