Repository iver-wharf/wharf-api, pull requests merged in 2021-11, with the labels that each got.

#102 Removed RabbitMQ integration
  CHANGELOG.md
  build.go
  config.go
  go.mod
  go.sum
  main.go
  messagequeue.go
  project.go
Labels: enhancement

#103 Create trivy-analysis.yml
  .github/workflows/trivy-analysis.yml
Labels: enhancement

#100 Migrate columns to `NOT NULL`
  CHANGELOG.md
  migrations.go
  pkg/model/database/database.go
Labels: enhancement

#99 Search via `GET /project`
  CHANGELOG.md
  branch.go
  go.mod
  go.sum
  internal/deprecated/project.go
  internal/ptrconv/ptrconv.go
  internal/wherefields/wherefields.go
  internal/wherefields/wherefields_example_test.go
  internal/wherefields/wherefields_test.go
  pkg/model/database/database.go
  pkg/model/request/request.go
  pkg/model/response/response.go
  pkg/modelconv/projectconv.go
  project.go
  utils.go
  utils_test.go
Labels: enhancement

#101 Allow cred/authorization header CORS
  CHANGELOG.md
  config.go
  main.go
Labels: enhancement

#110 Added Codacy exclude_paths for deprecated package
  .codacy.yml
Labels: enhancement

#113 Added missing PUT /branches endpoint registration
  CHANGELOG.md
  internal/deprecated/branch.go
Labels: bug

#108 Added database.SafeSQLName type
  pkg/model/database/database.go
  pkg/orderby/column.go
  pkg/orderby/example_test.go
  pkg/orderby/orderby_test.go
  pkg/orderby/slice.go
  project.go
  utils.go
Labels: enhancement

#112 Added RemoteProjectID to Project structs
  CHANGELOG.md
  pkg/model/database/database.go
  pkg/model/request/request.go
  pkg/model/response/response.go
  pkg/modelconv/projectconv.go
Labels: enhancement

#116 Updated .gitignore & .dockerignore
  .dockerignore
  .gitignore
Labels: enhancement

#106 Added `go test` & `goimports` actions
  .github/workflows/go-format.yml
  .github/workflows/go-test.yml
Labels: enhancement

#109 Added remaining GET search endpoints
  CHANGELOG.md
  artifact.go
  build.go
  internal/deprecated/artifact.go
  internal/deprecated/build.go
  internal/deprecated/project.go
  internal/deprecated/provider.go
  internal/deprecated/token.go
  internal/wherefields/wherefields.go
  main.go
  pkg/model/database/database.go
  pkg/model/response/response.go
  pkg/modelconv/artifactconv.go
  project.go
  provider.go
  token.go
  utils.go
  utils_gin.go
  utils_gorm.go
Labels: enhancement

#118 Paginated response fixes
  CHANGELOG.md
  artifact.go
  build.go
  internal/deprecated/project.go
  pkg/model/response/response.go
  project.go
  provider.go
  test_result.go
  token.go
Labels: enhancement

#111 Added CreatedAt and UpdatedAt
  CHANGELOG.md
  pkg/model/database/database.go
  pkg/model/response/response.go
  pkg/modelconv/artifactconv.go
  pkg/modelconv/branchconv.go
  pkg/modelconv/buildconv.go
  pkg/modelconv/metadataconv.go
  pkg/modelconv/projectconv.go
  pkg/modelconv/providerconv.go
  pkg/modelconv/testresultconv.go
  pkg/modelconv/tokenconv.go
  test_result.go
Labels: enhancement

#117 Project overrides
  CHANGELOG.md
  internal/coalesce/coalesce.go
  migrations.go
  pkg/model/database/database.go
  pkg/model/request/request.go
  pkg/model/response/response.go
  pkg/modelconv/projectconv.go
  project.go
Labels: enhancement

#120 Move endpoints
  CHANGELOG.md
  branch.go
  build.go
  internal/deprecated/branch.go
  internal/deprecated/build.go
  main.go
  pkg/model/request/request.go
  project.go
Labels: enhancement

#123 Fixed GET /project using providerJSONToColumns
  CHANGELOG.md
  project.go
Labels: bug

#122 Document endpoint versions
  artifact.go
  branch.go
  build.go
  internal/deprecated/artifact.go
  internal/deprecated/branch.go
  internal/deprecated/build.go
  internal/deprecated/project.go
  internal/deprecated/provider.go
  internal/deprecated/token.go
  ping.go
  project.go
  provider.go
  test_result.go
  token.go
  version.go
Labels: documentation
