Repository iver-wharf/wharf-api, pull requests merged in 2022-01, with the labels that each got.

#128 Appended /v5 to Go module
  CHANGELOG.md
  artifact.go
  branch.go
  build.go
  go.mod
  internal/deprecated/artifact.go
  internal/deprecated/branch.go
  internal/deprecated/build.go
  internal/deprecated/project.go
  internal/deprecated/provider.go
  internal/deprecated/token.go
  internal/set/strings_example_test.go
  internal/wherefields/wherefields_example_test.go
  main.go
  migrations.go
  ping.go
  pkg/modelconv/artifactconv.go
  pkg/modelconv/branchconv.go
  pkg/modelconv/buildconv.go
  pkg/modelconv/metadataconv.go
  pkg/modelconv/projectconv.go
  pkg/modelconv/projectconv_test.go
  pkg/modelconv/providerconv.go
  pkg/modelconv/testresultconv.go
  pkg/modelconv/tokenconv.go
  pkg/orderby/column.go
  pkg/orderby/example_test.go
  pkg/orderby/orderby_test.go
  pkg/orderby/slice.go
  project.go
  project_test.go
  provider.go
  test_result.go
  token.go
  utils.go
  utils_gin.go
  utils_gorm.go
  utils_test.go
Labels: enhancement

#129 Release v5.0.0
  CHANGELOG.md
Labels: release

#131 Preload test result summaries and params when getting list of builds
  CHANGELOG.md
  build.go
Labels: bug, enhancement
